LTO_ENABLE = yes
QMK_SETTINGS = no
KEY_OVERRIDE_ENABLE = no
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = no
VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes
VIAL_ENCODERS_ENABLE = yes
ENCODER_MAP_ENABLE = no
MIDI_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
# MOUSEKEY_ENABLE = no
# EXTRAKEY_ENABLE = no
# SPACE_CADET_ENABLE = no
# GRAVE_ESC_ENABLE = no
# MAGIC_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
MUSIC_ENABLE = no

