LTO_ENABLE = yes
QMK_SETTINGS = yes
TAP_DANCE_ENABLE = yes 
COMBO_ENABLE = yes

MIDI_ENABLE = yes

# RGB_MATRIX_ENABLE = yes
# RGB_MATRIX_DRIVER = WS2812
# WS2812_DRIVER = vendor

IOS_DEVICE_ENABLE = yes
