LTO_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes

QMK_SETTINGS = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes

MIDI_ENABLE = no
VIALRGB_ENABLE = yes

NO_USB_STARTUP_CHECK = yes
