/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0xFC, 0x26, 0xB8, 0xCF, 0xD9, 0x10, 0xB7, 0x2F}
#define MIDI_ADVANCED

#define USB_SUSPEND_WAKEUP_DELAY 200

#define DYNAMIC_KEYMAP_LAYER_COUNT 16
#define DYNAMIC_KEYMAP_MACRO_COUNT 32

#define MIDI_ADVANCED

/* pin-out RP2040 */
#undef MATRIX_ROW_PINS
#undef MATRIX_COL_PINS
#define MATRIX_ROW_PINS { GP5, GP0, GP6 }
#define MATRIX_COL_PINS { GP23, GP3, GP4 }
#undef ENCODERS_PAD_A
#undef ENCODERS_PAD_B
#define ENCODERS_PAD_B { GP26, GP22, GP20 }
#define ENCODERS_PAD_A { GP29, GP28, GP27 }
#ifdef RGBLIGHT_ENABLE
#undef RGB_DI_PIN
#define RGB_DI_PIN GP21
#endif

#ifdef RGB_MATRIX_ENABLE
#undef RGB_DI_PIN
#define RGB_DI_PIN GP21
#endif
