# LTO_ENABLE = yes
VIA_ENABLE = yes

ENCODER_MAP_ENABLE = yes

# QMK_SETTINGS = yes 
# TAP_DANCE_ENABLE = yes 
# COMBO_ENABLE = yes 

# MIDI_ENABLE = yes
# VIAL_ENABLE = yes
# VIAL_INSECURE = yes
# VIAL_ENCODERS_ENABLE = yes
