VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes
QMK_SETTINGS = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
MIDI_ENABLE = yes
VIAL_ENCODERS_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
BOOTMAGIC_ENABLE = yes

NO_USB_STARTUP_CHECK = yes

RGBLIGHT_ENABLE = yes
BACKLIGHT_ENABLE = no
# RGBLIGHT_DRIVER = WS2812
# RGB_MATRIX_ENABLE = no
# RGB_MATRIX_DRIVER = WS2812
WS2812_DRIVER = vendor

# VIALRGB_ENABLE = yes
