/* SPDX-License-Identifier: GPL-2.0-or-later */
#pragma once

// python3 util/vial_generate_keyboard_uid.py
#define VIAL_KEYBOARD_UID {0xB4, 0x90, 0x72, 0x18, 0xE9, 0x4E, 0x10, 0x68}
// #define MIDI_ADVANCED

#define USB_SUSPEND_WAKEUP_DELAY 200

#undef FORCE_NKRO
#define FORCE_NKRO

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE

#define NO_MUSIC_MODE
#define LAYER_STATE_8BIT

#define USB_MAX_POWER_CONSUMPTION 100
#define DYNAMIC_KEYMAP_MACRO_COUNT 8
#define DYNAMIC_KEYMAP_LAYER_COUNT 8

// #undef RGBLIGHT_ANIMATIONS
// #undef RGBLIGHT_EFFECT_BREATHING
// #undef RGBLIGHT_EFFECT_RAINBOW_MOOD
// #undef RGBLIGHT_EFFECT_RAINBOW_SWIRL
#undef RGBLIGHT_EFFECT_SNAKE
#undef RGBLIGHT_EFFECT_KNIGHT
#undef RGBLIGHT_EFFECT_CHRISTMAS
// #undef RGBLIGHT_EFFECT_STATIC_GRADIENT
#undef RGBLIGHT_EFFECT_RGB_TEST
#undef RGBLIGHT_EFFECT_ALTERNATING
#undef RGBLIGHT_EFFECT_TWINKLE
