LTO_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes
VIAL_ENCODERS_ENABLE = yes

QMK_SETTINGS = no
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no

# compress firmware more
# SPACE_CADET_ENABLE = no
# GRAVE_ESC_ENABLE = no 
# MAGIC_ENABLE = no
# AVR_USE_MINIMAL_PRINTF = yes
# MUSIC_ENABLE = no
