LTO_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes

QMK_SETTINGS = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes

MIDI_ENABLE = yes
VIALRGB_ENABLE = yes
VIAL_ENCODERS_ENABLE = yes
ENCODER_MAP_ENABLE = yes

# fix unresposive keypad after sleep
NO_USB_STARTUP_CHECK = yes
