LTO_ENABLE = yes
QMK_SETTINGS = yes 
TAP_DANCE_ENABLE = yes 
COMBO_ENABLE = yes 

VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes
VIAL_ENCODERS_ENABLE = yes

# RGB_MATRIX_DRIVER = WS2812
WS2812_DRIVER = vendor

MIDI_ENABLE = yes
