# MCU = RP2040
# BOOTLOADER = rp2040
# BOARD = GENERIC_RP_RP2040

VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes
QMK_SETTINGS = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
MIDI_ENABLE = yes
VIAL_ENCODERS_ENABLE = yes
ENCODER_MAP_ENABLE = yes
VIALRGB_ENABLE = yes
NO_USB_STARTUP_CHECK = yes

BOOTMAGIC_ENABLE = yes
RGBLIGHT_ENABLE = yes
RGB_MATRIX_ENABLE = no
RGB_MATRIX_DRIVER = WS2812
WS2812_DRIVER = vendor
